### ISSUE TITLE
Fail to generate a KeyPair with the given options

### ISSUE THREAD

**Issue by XavegX367** [Daanra/laravel-lets-encrypt#25]
Hello, I tried running the php artisan command but it returns the following error:

![error](https://user-images.githubusercontent.com/76949970/200788870-6712004c-8d02-419f-974c-1f892ff9bf91.png)

I saw the other thread with this error that was resolved by installing OpenSSL. I have got it enabled and php says it is enabled with a path to a openssl.cnf. The thing is that the path doesn't actually exist.

![openssl](https://user-images.githubusercontent.com/76949970/200788394-5a276a54-846b-4924-a0a7-c65b83d5f277.png)

I don't know if that is why the command doesn't work? I am very new with certificates...

**Comment by Daanra** [comment]
Yes, this is probably due to the OpenSSL library not being properly installed.

I'm afraid I can't help you with its installation as I have little knowledge about the Windows architecture.

But, are you hosting your domain from this Windows computer? The command should be run from the server that hosts the domain. So if you're actually hosting the domain on some Linux architecture, then you might have better luck with the OpenSSL installation.

**Comment by XavegX367** [comment]
Okay, so it indeed is hosted on a Windows Server and I didn't configure anything for OpenSSL, atleast that I am aware of...

**Comment by XavegX367** [comment]
I am using Laragon, it has a feature to automatically generate SSL certificates for the domains it runs. So is it possible Laragon configured it for me? I would like to change this config since I don't like the generated SSL certificates made by Laragon.

**Comment by XavegX367** [comment]
Alright so I fixed it by installing OpenSSL on the whole machine. I downloaded it from here: https://slproweb.com/products/Win32OpenSSL.html
