### ISSUE TITLE
Argument #8 ($subjectAlternativeNames) must be of type array, null given

### ISSUE THREAD

**Issue by lucasdcrk** [Daanra/laravel-lets-encrypt#28]
Hi, 

Thanks for providing this package!

After upgrading to 0.5.1 I encounter the following type error when trying to generating any SSL certificate:

`Daanra\LaravelLetsEncrypt\AcmePhp\Ssl\DistinguishedName::__construct(): Argument #8 ($subjectAlternativeNames) must be of type array, null given, called in /home/netweak-prod/htdocs/netweak.com/vendor/daanra/laravel-lets-encrypt/src/Jobs/RequestCertificate.php on line 4`

Using
`LetsEncrypt::certificate('mydomain.com')->create();`

Also tried without success either:
`LetsEncrypt::certificate('mydomain.com')->setSubjectAlternativeNames([])->create();`

Any idea where it would come from?

Regards,
Lucas

**Comment by lucasdcrk** [comment]
Seems to be a migration issue, for anyone looking
When you upgrade to >5.0 on your existing installation
run `php artisan vendor:publish `
and select Laravel Letsencrypt package to publish the new migrations

**Comment by jayo-exe** [comment]
I'm have a similar issue as above.  I needed to remove the `->default('[]')` from the migration that adds the new `subject_alternative_names` field, due to the fact that **Laravel disallows default values on JSON fields** and the migration failed to process as long as this was in place.  

This allows the migration to run, but causes new records in the database to pre-populate this field with `null`, causing the error as described above.

**Comment by dyoh777** [comment]
I had a similar issue and it wasn't apparent where the issue was, the new migration solved my problem too.
